source 'https://rubygems.org'
ruby '2.2.3'

gem 'sinatra'
gem 'shotgun'
gem 'capybara'
gem 'selenium-webdriver'
gem 'pry'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rspec'
gem 'rspec-sinatra'
gem 'database_cleaner'